# permissions to do viewer harborclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: harborcluster-viewer-role
rules:
- apiGroups:
  - cluster.goharbor.io
  resources:
  - harborclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.goharbor.io
  resources:
  - harborclusters/status
  verbs:
  - get
